/* =========================================================================
   MERGE STATS — after a fresh `generate-data.js` run (which rebuilds WHICH
   spots rank, but with REVIEWS_PROVIDER=none leaves hype/love null), carry
   the existing per-spot analysis over from the previous data file so only
   genuinely NEW spots need SerpAPI calls.

   Matching key: dish id + spot name. Manual/verified entries written by the
   generator are kept as-is (they always win). Prints what still needs a
   fill, so you know the SerpAPI cost before running fill-missing-stats.

       cp sf-food-data.js sf-food-data.prev.js   # snapshot BEFORE generating
       REVIEWS_PROVIDER=none node generate-data.js --top 5
       node merge-stats.js
       node fill-missing-stats.js                 # new spots only
   ========================================================================= */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

function load(file) {
  const ctx = { window: {} };
  vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(path.join(__dirname, file), "utf8"), ctx);
  return ctx.window.SF_FOOD_DATA;
}

const prev = load("sf-food-data.prev.js");
const next = load("sf-food-data.js");

const prevIndex = new Map();
for (const c of Object.values(prev.cuisines))
  for (const d of c.dishes)
    for (const s of d.spots)
      prevIndex.set(`${d.id}::${s.name.toLowerCase()}`, s);

let carried = 0, fresh = 0, kept = 0, dropped = 0, needsFill = [];
const nextNames = new Set();

for (const c of Object.values(next.cuisines)) {
  for (const d of c.dishes) {
    for (const s of d.spots) {
      nextNames.add(`${d.id}::${s.name.toLowerCase()}`);
      const old = prevIndex.get(`${d.id}::${s.name.toLowerCase()}`);
      if (s.dishApproval != null) { kept++; continue; } // generator wrote a manual/verified entry
      if (old && (old.dishApproval != null || old.dishMentions != null)) {
        s.dishMentions = old.dishMentions;
        s.dishApproval = old.dishApproval;
        s.dishSample = old.dishSample;
        s.dishChip = s.dishChip || old.dishChip;
        s.dishSource = old.dishSource;
        s.dishVerified = old.dishVerified;
        if (old.businessStatus) s.businessStatus = old.businessStatus;
        if (old._refreshedAt) s._refreshedAt = old._refreshedAt;
        // a fresh Places quote may be generic; prefer the old dish-specific one
        if (old.why && /Top-rated for/.test(s.why || "")) s.why = old.why;
        carried++;
      } else {
        fresh++;
        needsFill.push(`${d.id} · ${s.name}`);
      }
    }
  }
}
for (const key of prevIndex.keys()) if (!nextNames.has(key)) dropped++;

const out = `/* AUTO-GENERATED by generate-data.js; stats merged by merge-stats.js ${new Date().toISOString()}. Do not hand-edit. */\nwindow.SF_FOOD_DATA = ${JSON.stringify(next, null, 1)};\n`;
fs.writeFileSync(path.join(__dirname, "sf-food-data.js"), out);

console.log(`carried=${carried} manualKept=${kept} newSpotsNeedingFill=${fresh} droppedFromLists=${dropped}`);
console.log(`estimated SerpAPI cost for fills: ~${fresh * 6} searches`);
if (needsFill.length) console.log(needsFill.map((x) => "  fill: " + x).join("\n"));
